function onCreatePost()
set('ratingX', 0);
set('ratingY', 50);
set('numScoreX', 0);
set('numScoreY', 50);
set('timeBar.visible', false)
set('introSoundsSuffix', '-pixel')
set('timeBarBG.visible', false)
set('timeTxt.visible', false)
set('healthBar.alpha', 0)
set('healthBarBG.alpha', 0)
set('iconP1.alpha', 0)
set('iconP2.alpha', 0)
set('gf.alpha', 0)
set('glowNotes', true)
setOrder('dadGroup', getOrder('boyfriendGroup')+2)
setOrder('TextsDeleted1Group', getOrder('dadGroup')+7)
end

function onCreate()     
    makeLuaSprite('weebSky', 'raices/weebSky', -200, -860, 0.1, 0.1)
    scaleObject('weebSky', 20.3, 20.3)
    set('weebSky.alpha', 0.15)

    makeLuaSprite('FloatingThings', 'raices/FloatingThings', 210, 111, 0.1, 0.1)
    addAnim('FloatingThings', 'Move', 'Things0', 18, true)
    scaleObject('FloatingThings', 2.4, 2.4)
    set('FloatingThings.antialiasing', false)
    set('FloatingThings.alpha', 0)

    makeLuaSprite('bfs', 'raices/BFHappy', -520, -200, 0.1, 0.1)
    addAnim('bfs', 'Move', 'Happy0', 22, true)
    scaleObject('bfs', 1.5, 1.5)
    set('bfs.antialiasing', false)
    set('bfs.alpha', 0)

    makeLuaSprite('FlashBF2', 'raices/FlashBF', -100, 0, 0.1, 0.1)
    addAnim('FlashBF2','Move','Flash0',22,true)
    scaleObject('FlashBF2', 3.0, 3.0);
    set('FlashBF2.antialiasing', false);
    set('FlashBF2.alpha', 0)

    makeLuaSprite('weebSchool', 'raices/weebSchool', -10, 211, 0.6, 0.90)
    addAnim('weebSchool','Move','weebSchool0',18,true)
    scaleObject('weebSchool', 2.8, 2.8)
    set('weebSchool.antialiasing', false)
    set('weebSchool.alpha', 0)

    makeLuaSprite('weebSchoolG', 'raices/weebSchoolGlitch', -10, 211, 0.6, 0.90)
    addAnim('weebSchoolG','Move','weebSchoolglitch0',18,true)
    scaleObject('weebSchoolG', 2.8, 2.8)
    set('weebSchoolG.antialiasing', false)
    set('weebSchoolG.alpha', 0)

    makeLuaSprite('weebStreet', 'raices/weebStreet', -340, 110, 0.95, 0.95)
    addAnim('weebStreet','Move','weebStreet0',18,true)
    scaleObject('weebStreet', 3.4, 3.5);
    set('weebStreet.antialiasing', false)
    set('weebStreet.alpha', 0)

    makeLuaSprite('weebStreetG', 'raices/weebStreet', -340, 110, 0.95, 0.95)
    addAnim('weebStreetG','Move','weebStreetglitch0',18,true)
    scaleObject('weebStreetG', 3.4, 3.5)
    set('weebStreetG.antialiasing', false)
    set('weebStreetG.alpha', 0)

    makeLuaSprite('weebStreet2', 'raices/weebStreet2', -340, -230, 0.95, 0.95)
    scaleObject('weebStreet2', 3.4, 3.5)
    set('weebStreet2.antialiasing', false)
    set('weebStreet2.alpha', 0)

    makeLuaSprite('Particles_white', 'raices/Particles_white', -500, 100, 1, 1)
    addAnim('Particles_white', 'Move', 'Particles-Red0', 30, true)
    setBlendMode('Particles_white', 'SCREEN')
    scaleObject('Particles_white', 3, 3)
    set('Particles_white.antialiasing', false)
    setOrder('dadGroup', getOrder('Particles_whiteGroup')+9)

    makeLuaSprite('petals', 'raices/petals', -200, -40, 0.85, 0.85)
    addAnim('petals', 'petals2', 'PETALS ALL0', 24, true)
    scaleObject('petals', 6.0, 6.0)
    set('petals.antialiasing', false)
    set('petals.alpha', 0)

    makeLuaSprite('TextsDeleted1', 'raices/TextsDeleted', -715, 400)
    addAnim('TextsDeleted1','Move','deleted10',1,true)
    scaleObject('TextsDeleted1', 2.0, 2.0)
    set('TextsDeleted1.antialiasing', false)
    set('TextsDeleted1.alpha', 0)

    makeLuaSprite('TextsDeleted3', 'raices/TextsDeleted', 1280, 550)
    addAnim('TextsDeleted3','Move','deleted30',1,true)
    scaleObject('TextsDeleted3', 2.0, 2.0)
    set('TextsDeleted3.antialiasing', false)
    set('TextsDeleted3.alpha', 0)

    makeLuaSprite('TextsDeleted2', 'raices/TextsDeleted', -715, 690)
    addAnim('TextsDeleted2','Move','deleted20',1,true)
    scaleObject('TextsDeleted2', 2.0, 2.0)
    set('TextsDeleted2.antialiasing', false)
    set('TextsDeleted2.alpha', 0)

    makeLuaSprite('TextsDeleted4', 'raices/TextsDeleted', 1280, 840)
    addAnim('TextsDeleted4','Move','deleted40',1,true)
    scaleObject('TextsDeleted4', 2.0, 2.0)
    set('TextsDeleted4.antialiasing', false)
    set('TextsDeleted4.alpha', 0)

    makeLuaSprite('overlay', 'raices/overlay', -62, -40, 0, 0)
    scaleObject('overlay', 0.97, 1.1)
    set('overlay.antialiasing', false)

    makeLuaSprite('Coding', 'raices/Coding', 530, -140, 0.95, 0.95)
    addAnim('Coding','Move','texts0',22,false)
    scaleObject('Coding', 2.5, 2.5)
    set('Coding.antialiasing', false)
    set('Coding.alpha', 0)

    makeLuaSprite('Coding2', 'raices/TextsCode', 300, -260, 0.95, 0.95)
    addAnim('Coding2','Move','MovingTexts0',20,false)
    scaleObject('Coding2', 4.2, 4.2)
    set('Coding2.antialiasing', false)
    set('Coding2.alpha', 0)

    makeLuaSprite('StaticTV', 'raices/StaticTV', -140, 0)
    addAnim('StaticTV','Move','static',16,true)
    scaleObject('StaticTV', 3.0, 3.0)
    set('StaticTV.antialiasing', false)
    setBlendMode('StaticTV', 'MULTIPLY')
    set('StaticTV.alpha', 0.50)

    makeLuaSprite('FlashBF', 'raices/FlashBF', -160, 0)
    addAnim('FlashBF','Move','Flash0',22,true)
    scaleObject('FlashBF', 3.0, 3.0)
    set('FlashBF.antialiasing', false)
    set('FlashBF.alpha', 0)

    makeLuaSprite('admin', 'raices/admin', 0, 0, 0, 0)
    scaleObject('admin', 2.5, 2.5)
    screenCenter('admin', 'xy')
    set('admin.antialiasing', false)
    setCam('admin', 'other')
    set('admin.alpha', 0)

    makeLuaSprite('BFG2', 'raices/BFSGlitchs', 1135, 175, 0.95, 0.95)
    addAnim('BFG2', 'Move', 'BFSglitchs0', 24, false)
    scaleObject('BFG2', 3.5, 3.5)
    set('BFG2.antialiasing', false)
    set('BFG2.flipX', true)
    set('BFG2.alpha', 0)

    makeLuaSprite('BFG', 'raices/BFSGlitchs', 1135, 175, 0.95, 0.95)
    addAnim('BFG', 'Move', 'BFSglitchs0', 24, false)
    scaleObject('BFG', 3.5, 3.5)
    set('BFG.antialiasing', false)
    set('BFG.alpha', 0)

    makeLuaSprite('scanlines', 'scanlines', 0, -150)
    addAnim('scanlines', 'Move', 'scan0', 18, true)
    scaleObject('scanlines', 3.7, 3.7)
    setCam('scanlines', 'other')
    setBlendMode('scanlines', 'SUBTRACT')
    set('scanlines.alpha', 0)

    makeLuaSprite('BlackLiquid', 'raices/BlackLiquid', -850, -270)
    addAnim('BlackLiquid','Move','Anim0',43,false)
    scaleObject('BlackLiquid', 9.9, 9.9)
    setCam('BlackLiquid', 'other')
    set('BlackLiquid.antialiasing', false)
    set('BlackLiquid.alpha', 0)

    makeLuaSprite('StaticTV2', 'raices/StaticTV', 0, -130, 0, 0)
    addAnim('StaticTV2','Move','static',16,true)
    scaleObject('StaticTV2', 3.0, 3.0)
    set('StaticTV2.antialiasing', false)
    set('StaticTV2.alpha', 0)

    makeColorBox('black', 0, 0, 1, 1, '000000')
    scroll('black', 0, 0)
    scaleObject('black', 0.67, 0.67)
    set('black.alpha', 0)

    makeLuaSprite('tv', 'raices/tv', 0, 0)
    scaleObject('tv', 0.67, 0.67)
    screenCenter('tv', 'xy')
    setCam('tv', 'hud')

    makeLuaSprite('tv2', 'raices/tv', 0, 0)
    scaleObject('tv2', 0.67, 0.67)
    screenCenter('tv2', 'xy')
    set('tv2.alpha', 0)

    makeLuaSprite('Blue', 'raices/BlueScreen', 0, 0)
    scaleObject('Blue', 1.1, 1.1)
    screenCenter('Blue', 'xy')
    setCam('Blue', 'other')
    set('Blue.alpha', 0)

    makeLuaSprite('BlackLiquid2', 'raices/BlackLiquid2', -13, 0, 0, 0)
    addAnim('BlackLiquid2','Move','Liquidmove0',37,false)
    scaleObject('BlackLiquid2', 13, 13.9)
    setCam('BlackLiquid2', 'other')
    set('BlackLiquid2.antialiasing', false)
    set('BlackLiquid2.alpha', 0)

    makeLuaSprite('bf1', 'raices/bf1', 0, -40)
    scaleObject('bf1', 9.5, 9.5)
    set('bf1.antialiasing', false)
    setCam('bf1', 'other')
    set('bf1.alpha', 0)

    makeLuaSprite('bf2', 'raices/bf2', 600, 90)
    scaleObject('bf2', 7.5, 7.5)
    set('bf2.antialiasing', false)
    setCam('bf2', 'other')
    set('bf2.alpha', 0)

    makeLuaSprite('bf3', 'raices/bf3', 88, 280)
    scaleObject('bf3', 5.5, 5.5)
    set('bf3.antialiasing', false)
    setCam('bf3', 'other')
    set('bf3.alpha', 0)

    makeLuaSprite('bf4', 'raices/bf4', 720, 90)
    scaleObject('bf4', 6.5, 6.5)
    set('bf4.antialiasing', false)
    setCam('bf4', 'other')
    set('bf4.alpha', 0)

    makeLuaSprite('bf5', 'raices/bf5', 440, 150)
    scaleObject('bf5', 5.4, 5.4)
    set('bf5.antialiasing', false)
    setCam('bf5', 'other')
    set('bf5.alpha', 0)

    makeLuaSprite('bf6', 'raices/bf6', -99, -90)
    scaleObject('bf6', 12.2, 12.2)
    set('bf6.antialiasing', false)
    setCam('bf6', 'other')
    set('bf6.alpha', 0)

    makeLuaSprite('StaticTV3', 'raices/StaticTV', 0, -130, 0, 0)
    addAnim('StaticTV3','Move','static',16,true)
    scaleObject('StaticTV3', 3.0, 3.0)
    setCam('StaticTV3', 'other')
    set('StaticTV3.antialiasing', false)
    set('StaticTV3.alpha', 0)

    makeColorBox('void', 0, 0, 1, 1, '000000')
    scroll('void', 0.0, 0.0)
    scaleObject('void', 1.9, 1.9)
    setCam('void', 'other')
    set('void.alpha', 0)

	-- sprites that only load if Low Quality is turned off
	
	add('weebSky', false)
	add('FloatingThings', false)
        add('bfs', false)
	add('FlashBF2', false)
	add('weebSchool', false)
	add('weebStreet', false)
	add('weebSchoolG', false)
	add('weebStreetG', false)
	add('weebStreet2', false)
        add('Particles_white', true)
	add('petals', true)
	add('TextsDeleted1', true)
	add('TextsDeleted3', true)
	add('TextsDeleted2', true)
	add('TextsDeleted4', true)
	add('overlay', true)
	add('Coding', false)
	add('Coding2', false)
	add('BFG2', false)
	add('BFG', false)
        add('scanlines', false)
	add('FlashBF', true)
	add('StaticTV', true)
	add('StaticTV2', true)
	add('black', false)
	add('BlackLiquid', false)
	add('tv2', true)
	add('admin', true)
	add('tv', true)
	add('Blue', true)
	add('BlackLiquid2', true)
	add('bf1', true)
	add('bf2', true)
	add('bf3', true)
	add('bf4', true)
	add('bf5', true)
	add('bf6', true)
	add('StaticTV3', true)
        add('void', false)

end